name: "Build & Deploy to Netlify"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing Nix
      uses: cachix/install-nix-action@v8
    - name: Update content
      run: ./update.sh
    - name: Building nixos.org
      run: nix build && mkdir build && cp -RL ./result/* ./build/
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.0.5
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        publish-dir: './build'
        production-branch: 'master'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: 'Deploy from GitHub Actions'
      if: github.repository == 'NixOS/nixos-homepage'
    - name: Commit flake.lock and push to master branch
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'test'
        commit-message: 'Update flake.lock [CI Skip]'
        force-add: 'true'
        files: flake.lock
